version: 0.0 # 파일 버전. 현재 이 버전만 지원
os: linux

environment:
  variables:
    FIREBASE_CREDENTIALS_B64: "{{ FIREBASE_CREDENTIALS_B64 }}"

files: # 배포할 파일 및 디렉토리 정의
  - source: /
    destination: /home/ubuntu/muzigi # 코드를 복사할 EC2 경로
permissions:
  - object: /home/ubuntu/muzigi
    pattern: "**" # 권한 적용할 파일의 패턴. 모든 파일.
    owner: ubuntu
    group: ubuntu
    mode: 755
    
hooks:
  BeforeInstall: # 배포 전 - 이전 버전 중지 및 환경 정리
    - location: scripts/before_install.sh
      timeout: 300 # 스크립트 제한 시간
      runas: ubuntu

  AfterInstall: # 배포 후 실행
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart: # 애플리케이션 시작 시 의존성 설치, 실행 등
    - location: scripts/application_start.sh
      timeout: 120
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
